name: Check C++ Build

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-apps:
    runs-on: ubuntu-latest

    steps:
    - name: download source code 
      uses: actions/checkout@v4
    - name: Install Qt 6.8
      uses: jurplel/install-qt-action@v4
      with: 
        version: "6.8.0"
        modules: qtcharts 
    - name: install libs
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        sudo apt-get install -y libsqlite3-dev libdbus-1-dev libglib2.0-dev
        sudo apt-get install -y libpaho-mqtt-dev
    - name: configure cmake
      run: |
        cd apps
        cmake -B build -S .
    - name: compile
      run: |
        cd apps
        cmake --build build -j4

  build-firmwares:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fw_path:
          - "firmware/esp32-mesh/node_ble_mesh_actuator_ac_r"
          - "firmware/esp32-mesh/provisioner"
          - "firmware/esp32-mesh/rpr_server"
    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: build firmware esp32
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: "release-v5.1"
        target: "esp32"
        path: "${{ matrix.fw_path }}"
      
